import frameself.format.*;
import java.util.Date;

rule "HousePersonInRfc"
	when
		Symptom(category == "HouseState:PersonIn", $value: value)
	then
		Rfc rfcLED = new Rfc();
		rfcLED.setCategory("SwitchOnLEDIn");
		rfcLED.setValue($value);
		rfcLED.setTimestamp(new Date());
		rfcLED.setExpiry(new Date(System.currentTimeMillis()+4000));
		insert(rfcLED);
end

rule "HousePersonOutRfc"
	when
		Symptom(category == "HouseState:PersonOut", $value: value)
	then
		Rfc rfcLED = new Rfc();
		rfcLED.setCategory("SwitchOnLEDOut");
		rfcLED.setValue($value);
		rfcLED.setTimestamp(new Date());
		rfcLED.setExpiry(new Date(System.currentTimeMillis()+4000));
		insert(rfcLED);
end

rule "HouseEmptyRfc"
	when
		Symptom(category == "HouseState:Empty")
	then
		Rfc rfcLight = new Rfc();
		rfcLight.setCategory("SwitchOffLights");
		rfcLight.setTimestamp(new Date());
		rfcLight.setExpiry(new Date(System.currentTimeMillis()+4000));
		Rfc rfcLED = new Rfc();
		rfcLED.setCategory("SwitchOffLED");
		rfcLED.setTimestamp(new Date());
		rfcLED.setExpiry(new Date(System.currentTimeMillis()+4000));
		insert(rfcLED);
		insert(rfcLight);
end

rule "HouseNotEmptyRfc"
	when
		Symptom(category == "HouseState:NotEmpty")
	then
		Rfc rfcLight = new Rfc();
		rfcLight.setCategory("SwitchOnLights");
		rfcLight.setTimestamp(new Date());
		rfcLight.setExpiry(new Date(System.currentTimeMillis()+4000));
		insert(rfcLight);
end

