import frameself.format.*;
import java.util.Date;
import frameself.house.*;

rule "add SwitchOnLights"
    when
       Event($id: id, category == "HousePerson",  $value: value)  
    then
      Symptom symptom = new Symptom();
		symptom.setCategory("PersonInsideHouse");
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis()+4000));
      insert(symptom);  
end

rule "add SwitchOffLights"
    when
       Event($id: id, category == "HouseEmpty")  
    then
      Symptom symptom = new Symptom();
		symptom.setCategory("NoPersonInsideHouse");
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis()+4000));
      insert(symptom);  
end