import frameself.format.*;
import java.util.Date;
import frameself.house.*;

rule "PersonAuthentified"
	when
		Event(category == "RFID" , $value: value)
		and Event(category == "IR")
		and Event(category == "Pressure")
	then
		HouseManager houseManager = HouseManager.getInstance();
		String houseManagerCategory = houseManager.updatePersonsInHouse($value);
		Symptom symptom = new Symptom();
		symptom.setCategory(houseManagerCategory);
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end

rule "PersonNotAuthentified"
	when
		(Event(category == "IR") or Event(category == "Pressure"))
	    and not (Event(category == "RFID"))
	then
		Symptom symptom = new Symptom();
		symptom.setCategory("HouseState:Intruder");
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end