import frameself.format.*;
import java.util.Date;
import frameself.house.*;

rule "PersonAuthentified"
	when
		Event(category == "RFID" , $value: value)
		and Event(category == "IR", priority == 1)
		and Event(category == "Pressure", priority == 1)
	then
		HouseManager houseManager = HouseManager.getInstance();
		String houseManagerCategory = houseManager.updatePersonsInHouse($value);
		Symptom symptom = new Symptom();
		symptom.setCategory(houseManagerCategory);
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		String houseManagerCategory2 = houseManager.PersonInOrOut();
		Symptom symptom2 = new Symptom();
		symptom2.setCategory(houseManagerCategory2);
		symptom2.setTimestamp(new Date());
		symptom2.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
		insert(symptom2);
end

rule "VocalCommand"
	when
		Event(category == "VocalRecognition", $value: value)
	then
		Symptom symptom = new Symptom();
		symptom.setCategory("CommandRecognized");
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end

rule "PersonNotAuthentified"
	when
		(Event(category == "IR", priority == 0) or Event(category == "Pressure", priority == 0))
	    and not (Event(category == "RFID"))
	then
		Symptom symptom = new Symptom();
		symptom.setCategory("HouseState:Intruder");
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end

