import frameself.format.*;
import java.util.Date;

rule "add HighLuminosity"
    when
       Event($id: id, category == "Luminosity",  $value: value, Integer.parseInt(value) > 400)  
    then
       	Symptom symptom = new Symptom();
		symptom.setCategory("HighLuminosity");
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis()+4000));
		insert(symptom);  
end

rule "add DecreaseLight symptom"
	when
		Event($id: id, category == "Luminosity", $value: value, Integer.parseInt(value) < 400)
	then
		Symptom symptom = new Symptom();
		symptom.setCategory("LowLuminosity");
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end
