import frameself.format.*;
import java.util.Date;
import frameself.house.*;

rule "RFIDTag"
	when
		Event($id: id, category == "Sensors", $value: value)
	then
		HouseManager = new HouseManager();
		Symptom symptom = new Symptom();
		symptom.setCategory("LowLuminosity");
		symptom.setValue($value);
		symptom.setTimestamp(new Date());
		symptom.setExpiry(new Date(System.currentTimeMillis() + 4000));
		insert(symptom);
end
